language: python
python:
- '3.6'
- '3.5'
- '3.4'
- '3.3'
- '2.7'
sudo: false
install:
- pip install .
script:
- python -m unittest discover -v -s gtts/tests/
deploy:
  provider: pypi
  user: pndurette
  password:
    secure: GTbUTja0D/LDnIxLLO4ohTHGugwrnx2nMqAw5n7a9JAsfxCVXz6+vu0fkNBmOSJV0bNsFcoj/Q+lcR1SCNsw2NibWWFLDMoYD/yqP/SrHTSUoTXt+o7H9/qvxR2MDr0t2S5kjAux4bw5uPg8WtYlPpD0VWgWkFCm3JmJG+cG1tA=
  on:
    tags: true
    distributions: sdist
    repo: pndurette/gTTS
    branch: master
    python: '3.4'
